### ISSUE TITLE
Javascript Error in the template report.html

### ISSUE THREAD

**Issue by netnic0** [rpii/wdio-html-reporter#79]
Hi,
To Fix:
It seems to have an error at the end of the template file of the report.html.
I have this error in my broaser console:
Uncaught SyntaxError: Unexpected token ')'

    ```
    if () {
            document.querySelectorAll('.suite-header').forEach(item => {
                item.click();
            });
        }
```
I think it must be 
      ```
  if (true) {
            document.querySelectorAll('.suite-header').forEach(item => {
                item.click();
            });
        }
```

**Comment by rpii** [comment]
The conditional is evaluated by handlebars:

if ({{ ifCollapseTests() }}) {
    document.querySelectorAll('.test-header').forEach(item => {
        item.click();
    });
}
if ({{ ifCollapseSuites() }}) {
    document.querySelectorAll('.suite-header').forEach(item => {
        item.click();
    });
}


environment.addGlobal('ifCollapseTests', (text:string) => {
    return reportOptions.collapseTests;
});

environment.addGlobal('ifCollapseSuites', (text:string) => {
    return reportOptions.collapseSuites;
});


You should define the two variables in report options.  They are defaulted
however, so that should not happen.

Rich

**Comment by netnic0** [comment]
Ok, I understand.
Thanks!
Nicolas
